[33mWARNING[0m:  [21-06-2025 17:29:48] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048575. chroma_server_nofile will not be set.
[32mINFO[0m:     [21-06-2025 17:29:48] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [21-06-2025 17:29:48] Starting component System
[36mDEBUG[0m:    [21-06-2025 17:29:48] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [21-06-2025 17:29:48] Starting component SqliteDB
[36mDEBUG[0m:    [21-06-2025 17:29:48] Starting component QuotaEnforcer
[36mDEBUG[0m:    [21-06-2025 17:29:48] Starting component Posthog
[36mDEBUG[0m:    [21-06-2025 17:29:48] Starting component LocalSegmentManager
[36mDEBUG[0m:    [21-06-2025 17:29:48] Starting component SegmentAPI
[32mINFO[0m:     [21-06-2025 17:29:48] Started server process [[36m8288[0m]
[32mINFO[0m:     [21-06-2025 17:29:48] Waiting for application startup.
[32mINFO[0m:     [21-06-2025 17:29:48] Application startup complete.
[32mINFO[0m:     [21-06-2025 17:29:48] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [21-06-2025 17:30:04] ::1:52667 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:30:04] ::1:52667 - "POST /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:30:15] ::1:52671 - "GET /api/v1/collections HTTP/1.1" 200
[36mDEBUG[0m:    [21-06-2025 17:30:15] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [21-06-2025 17:30:15] ::1:52671 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/add HTTP/1.1" 201
[32mINFO[0m:     [21-06-2025 17:35:05] ::1:52693 - "GET /api/v1/collections HTTP/1.1" 200
[31mERROR[0m:    [21-06-2025 17:35:05] Collection maintstar-docs already exists
Traceback (most recent call last):
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 156, in call_next
    raise app_exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "/Users/juliareinhart/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 156, in call_next
    raise app_exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 630, in create_collection
    await to_thread.run_sync(
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 620, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/api/segment.py", line 173, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/db/mixins/sysdb.py", line 220, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection maintstar-docs already exists
[32mINFO[0m:     [21-06-2025 17:35:05] ::1:52693 - "POST /api/v1/collections HTTP/1.1" 500
[32mINFO[0m:     [21-06-2025 17:35:11] ::1:52695 - "GET /api/v1/collections HTTP/1.1" 200
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-0
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-1
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-2
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-3
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-4
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-5
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-6
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-7
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-8
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-9
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-10
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-11
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-12
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-13
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-14
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-15
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-16
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-17
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-18
[33mWARNING[0m:  [21-06-2025 17:35:11] Insert of existing embedding ID: CH1-Work Orders.md-chunk-19
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-0
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-1
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-2
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-3
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-4
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-5
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-6
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-7
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-8
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-9
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-10
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-11
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-12
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-13
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-14
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-15
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-16
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-17
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-18
[33mWARNING[0m:  [21-06-2025 17:35:11] Add of existing embedding ID: CH1-Work Orders.md-chunk-19
[32mINFO[0m:     [21-06-2025 17:35:11] ::1:52695 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/add HTTP/1.1" 201
[32mINFO[0m:     [21-06-2025 17:35:11] ::1:52695 - "GET /api/v1/collections HTTP/1.1" 200
[31mERROR[0m:    [21-06-2025 17:35:11] Collection maintstar-docs already exists
Traceback (most recent call last):
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 156, in call_next
    raise app_exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "/Users/juliareinhart/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 156, in call_next
    raise app_exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 630, in create_collection
    await to_thread.run_sync(
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 620, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/api/segment.py", line 173, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/db/mixins/sysdb.py", line 220, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection maintstar-docs already exists
[32mINFO[0m:     [21-06-2025 17:35:11] ::1:52695 - "POST /api/v1/collections HTTP/1.1" 500
[32mINFO[0m:     [21-06-2025 17:35:12] ::1:52695 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:35:12] ::1:52695 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/add HTTP/1.1" 201
[32mINFO[0m:     [21-06-2025 17:38:18] ::1:53185 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:38:18] ::1:53185 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:38:31] ::1:53189 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:38:31] ::1:53189 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:39:25] ::1:53211 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:39:25] ::1:53211 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:39:42] ::1:53214 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:39:42] ::1:53214 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:40:08] ::1:53226 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:40:08] ::1:53226 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:40:22] ::1:53229 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:40:22] ::1:53229 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:40:37] ::1:53233 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:40:37] ::1:53233 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:41:09] ::1:53236 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:41:09] ::1:53236 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:41:35] ::1:53240 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:41:35] ::1:53240 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:41:53] ::1:53244 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:41:53] ::1:53244 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:42:17] ::1:53247 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:42:17] ::1:53247 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:42:55] ::1:53250 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:42:55] ::1:53250 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:44:40] ::1:53265 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:44:40] ::1:53265 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:45:05] ::1:53270 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:45:05] ::1:53270 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:45:33] ::1:53274 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:45:33] ::1:53274 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:45:50] ::1:53277 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:45:50] ::1:53277 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:46:03] ::1:53281 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:46:03] ::1:53281 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:46:23] ::1:53284 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:46:23] ::1:53284 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:46:34] ::1:53287 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:46:34] ::1:53287 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:46:50] ::1:53290 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:46:50] ::1:53290 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:47:13] ::1:53293 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:47:13] ::1:53293 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:47:27] ::1:53296 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:47:27] ::1:53296 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:47:43] ::1:53299 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:47:43] ::1:53299 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:48:00] ::1:53302 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:48:00] ::1:53302 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:48:24] ::1:53305 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:48:24] ::1:53305 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:48:35] ::1:53316 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:48:35] ::1:53316 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:48:51] ::1:53322 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:48:51] ::1:53322 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:49:08] ::1:53326 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:49:08] ::1:53326 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:49:15] ::1:53327 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:49:15] ::1:53327 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:49:39] ::1:53330 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:49:39] ::1:53330 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:50:06] ::1:53333 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:50:06] ::1:53333 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:50:23] ::1:53336 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:50:23] ::1:53336 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:51:12] ::1:53362 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:51:12] ::1:53362 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:51:36] ::1:53366 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:51:36] ::1:53366 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:51:46] ::1:53371 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:51:46] ::1:53371 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:51:51] ::1:53372 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:51:51] ::1:53372 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:52:01] ::1:53375 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:52:01] ::1:53375 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:52:16] ::1:53378 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:52:16] ::1:53378 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:55:16] ::1:53396 - "GET /api/v1/collections HTTP/1.1" 200
[31mERROR[0m:    [21-06-2025 17:55:16] Collection maintstar-docs already exists
Traceback (most recent call last):
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 156, in call_next
    raise app_exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "/Users/juliareinhart/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 156, in call_next
    raise app_exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 630, in create_collection
    await to_thread.run_sync(
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 620, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/api/segment.py", line 173, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/db/mixins/sysdb.py", line 220, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection maintstar-docs already exists
[32mINFO[0m:     [21-06-2025 17:55:16] ::1:53396 - "POST /api/v1/collections HTTP/1.1" 500
[32mINFO[0m:     [21-06-2025 17:55:21] ::1:53396 - "GET /api/v1/collections HTTP/1.1" 200
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-0
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-1
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-2
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-3
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-4
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-5
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-6
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-7
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-8
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-9
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-10
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-11
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-12
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-13
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-14
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-15
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-16
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-17
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-18
[33mWARNING[0m:  [21-06-2025 17:55:21] Insert of existing embedding ID: CH1-Work Orders.md-chunk-19
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-0
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-1
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-2
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-3
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-4
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-5
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-6
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-7
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-8
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-9
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-10
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-11
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-12
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-13
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-14
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-15
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-16
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-17
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-18
[33mWARNING[0m:  [21-06-2025 17:55:21] Add of existing embedding ID: CH1-Work Orders.md-chunk-19
[32mINFO[0m:     [21-06-2025 17:55:21] ::1:53396 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/add HTTP/1.1" 201
[32mINFO[0m:     [21-06-2025 17:55:21] ::1:53396 - "GET /api/v1/collections HTTP/1.1" 200
[31mERROR[0m:    [21-06-2025 17:55:21] Collection maintstar-docs already exists
Traceback (most recent call last):
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 148, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 156, in call_next
    raise app_exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "/Users/juliareinhart/anaconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_utils.py", line 82, in collapse_excgroups
    raise exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 156, in call_next
    raise app_exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 630, in create_collection
    await to_thread.run_sync(
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/server/fastapi/__init__.py", line 620, in process_create_collection
    return self._api.create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/api/segment.py", line 173, in create_collection
    coll, created = self._sysdb.create_collection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/juliareinhart/anaconda3/lib/python3.11/site-packages/chromadb/db/mixins/sysdb.py", line 220, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection maintstar-docs already exists
[32mINFO[0m:     [21-06-2025 17:55:21] ::1:53396 - "POST /api/v1/collections HTTP/1.1" 500
[32mINFO[0m:     [21-06-2025 17:55:22] ::1:53396 - "GET /api/v1/collections HTTP/1.1" 200
[33mWARNING[0m:  [21-06-2025 17:55:22] Insert of existing embedding ID: Work Order FAQ Questions.md-chunk-0
[33mWARNING[0m:  [21-06-2025 17:55:22] Insert of existing embedding ID: Work Order FAQ Questions.md-chunk-1
[33mWARNING[0m:  [21-06-2025 17:55:22] Insert of existing embedding ID: Work Order FAQ Questions.md-chunk-2
[33mWARNING[0m:  [21-06-2025 17:55:22] Insert of existing embedding ID: Work Order FAQ Questions.md-chunk-3
[33mWARNING[0m:  [21-06-2025 17:55:22] Insert of existing embedding ID: Work Order FAQ Questions.md-chunk-4
[33mWARNING[0m:  [21-06-2025 17:55:22] Add of existing embedding ID: Work Order FAQ Questions.md-chunk-0
[33mWARNING[0m:  [21-06-2025 17:55:22] Add of existing embedding ID: Work Order FAQ Questions.md-chunk-1
[33mWARNING[0m:  [21-06-2025 17:55:22] Add of existing embedding ID: Work Order FAQ Questions.md-chunk-2
[33mWARNING[0m:  [21-06-2025 17:55:22] Add of existing embedding ID: Work Order FAQ Questions.md-chunk-3
[33mWARNING[0m:  [21-06-2025 17:55:22] Add of existing embedding ID: Work Order FAQ Questions.md-chunk-4
[32mINFO[0m:     [21-06-2025 17:55:22] ::1:53396 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/add HTTP/1.1" 201
[32mINFO[0m:     [21-06-2025 17:56:08] ::1:53413 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 17:56:08] ::1:53413 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 18:45:27] ::1:53827 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 18:45:27] ::1:53827 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 18:45:56] ::1:53830 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 18:45:56] ::1:53830 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 18:46:22] ::1:53834 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 18:46:22] ::1:53834 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 18:46:45] ::1:53838 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 18:46:45] ::1:53838 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 19:01:43] ::1:53948 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 19:01:43] ::1:53948 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 19:02:02] ::1:53952 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 19:02:02] ::1:53952 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 19:02:27] ::1:53956 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 19:02:27] ::1:53956 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 19:02:52] ::1:53968 - "GET /api/v1/collections HTTP/1.1" 200
[32mINFO[0m:     [21-06-2025 19:02:52] ::1:53968 - "POST /api/v1/collections/f61f865b-75a2-446d-8195-edca78283a9d/query HTTP/1.1" 200
[32mINFO[0m:     [22-06-2025 12:23:16] Shutting down
[32mINFO[0m:     [22-06-2025 12:23:16] Waiting for application shutdown.
[36mDEBUG[0m:    [22-06-2025 12:23:16] Stopping component System
[36mDEBUG[0m:    [22-06-2025 12:23:16] Stopping component SegmentAPI
[36mDEBUG[0m:    [22-06-2025 12:23:16] Stopping component PersistentLocalHnswSegment
[36mDEBUG[0m:    [22-06-2025 12:23:16] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [22-06-2025 12:23:16] Stopping component Posthog
[36mDEBUG[0m:    [22-06-2025 12:23:16] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [22-06-2025 12:23:16] Stopping component SqliteDB
[36mDEBUG[0m:    [22-06-2025 12:23:16] Stopping component OpenTelemetryClient
[32mINFO[0m:     [22-06-2025 12:23:16] Application shutdown complete.
[32mINFO[0m:     [22-06-2025 12:23:16] Finished server process [[36m8288[0m]
